[build]
  functions = "react_netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/subscribe"
  to = "/.netlify/functions/subscribe"
  status = 200

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200