name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: Metatronsdoob369
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert owner name to lowercase
      id: string
      uses: vishalmamidi/lowercase-action@v1
      with:
        string: ${{ github.repository_owner }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./agents
        file: ./agents/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ steps.string.outputs.lowercase }}/clay-i-agent:latest
          ghcr.io/${{ steps.string.outputs.lowercase }}/clay-i-agent:v15
