name: Docker Image CI
# Docker Hub authentication configured with correct username

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Convert owner name to lowercase
      id: string
      uses: vishalmamidi/lowercase-action@v1
      with:
        string: ${{ github.repository_owner }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./agents
        file: ./agents/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/clay-i-agent:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/clay-i-agent:v15
